// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDB_F-7rYEk5JFIXiHOr_PsY12pJoHK5BI',
    appId: '1:289569686727:web:8840a90bc8bd5dfedfeae2',
    messagingSenderId: '289569686727',
    projectId: 'msft-essths-app',
    authDomain: 'msft-essths-app.firebaseapp.com',
    storageBucket: 'msft-essths-app.appspot.com',
    measurementId: 'G-C15KHRZC62',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgXbTDSUNaBoOL-jYYigXGP3d3nlW7l4c',
    appId: '1:289569686727:android:e3892558990386f5dfeae2',
    messagingSenderId: '289569686727',
    projectId: 'msft-essths-app',
    storageBucket: 'msft-essths-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCT_N10e4FaSpOOS8wTJNA-3ALZ1t2-SXg',
    appId: '1:289569686727:ios:cb18ad283abcc672dfeae2',
    messagingSenderId: '289569686727',
    projectId: 'msft-essths-app',
    storageBucket: 'msft-essths-app.appspot.com',
    iosClientId: '289569686727-ukkbdhr4cnl1l059sa10c60cs5p5ea8b.apps.googleusercontent.com',
    iosBundleId: 'com.msftessthsapp.microsoftEssthsApp',
  );
}
